stages:
  - test
  - build
  - deploy

application test:
  image: node
  stage: test
  script:
    - npm run test

application build:
  image: node
  stage: build
  script:
    - npm install

deployment:
  image: ruby:latest
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$APP_NAME --api_key=$API_KEY
  only: main

